GoogleAnalytics = ""
baseURL = "http://balaramadurai.github.io/"
canonifyURLs = true
languageCode = "en-us"
subtitle = "Travel theme for Hugo with Slider"
theme = "hugo-travelify-theme"
title = "Travelify"
[[menu.main]]
name = "cOntact3"
parent = "contact"
url = "/contact/"
weight = 1
[[menu.main]]
name = "Contact2"
parent = "contact"
url = "/contact/"
weight = 2
[[menu.main]]
name = "Contact21"
parent = "Contact2"
url = "/contact/"
weight = 2
[[menu.main]]
name = "cOntact22"
parent = "Contact2"
url = "/contact/"
weight = 1
[[menu.main]]
name = "contact"
url = "/contact/"
weight = 3
[[menu.main]]
name = "About"
url = "/about/"
weight = 1
[params]
author = "nikimonikado"
copyright = "Copyright"
custom_css = []
custom_js = []
date_format = "02 January, 2006"
disable_mathjax = true
logo = "logo.png"
site_description = "Travel theme for Hugo with Slider"
title_in_logo = true
[params.privacy]
DisqusShortname = "example"
enable = true
facebook_like = true
[params.share]
email = true
enable = true
facebook = true
linkedin = true
twitter = true
[params.slider]
enable = true
manual = false
num_features = 6
[params.widgets]
archives = false
author = true
categories = true
mailchimp = true
mailchimpform = "//balaramadurai.us15.list-manage.com/subscribe/post?u=7f4183fa2fe7abe3dc9f4efad&amp;id=49a3dd3745"
recent_articles = true
search = true
tag_cloud = true
tags = true
[permalinks]
categories = "/categories/:slug/"
tags = "/tags/:slug/"
[social]
email = "joe@example.com"
facebook = "example"
flickr = "example"
github = "example"
instagram = "example"
linkedin = "example"
pinterest = "example"
rss = "Needed"
tumblr = "example"
twitter = "example"
vimeo = "example"
youtube = "example"
[taxonomies]
author = "author"
category = "categories"
series = "series"
tag = "tags"
